### ISSUE TITLE
TODO for JHipster v5

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-online#35]
- [x] Remove the "social login" option
- [x] Add the React option
- [x] A gateway with OAuth2/UAA needs to have a database (at least for now)
- [x] When OAuth2 is selected, you cannot select Cassandra
